### ISSUE TITLE
Remove the google analytics

### ISSUE THREAD

**Issue by RizRiyz** [0x27/0x27.github.io#1]
Hey man, thanks for using naringu template, can you help me remove the Google analytics ID listed [here](https://github.com/0x27/0x27.github.io/blob/master/_includes/analytics.html) ?

Thanks 💃

**Comment by 0x27** [comment]
Done :) Somehow I missed that in the template!

Also, *awesome* theme. Was just what I was looking for :D

**Comment by RizRiyz** [comment]
Thanks, good to see you happy with that theme. Keep it up!
